import type { Client, Payment } from './types';

export const clients: Client[] = [
  {
    id: 'c1',
    name: 'Arjun Mehta',
    business: 'TechStar Solutions',
    phone: '+91 98765 43210',
    email: 'arjun@techstar.in',
    service: 'both',
    createdAt: '2026-07-10',
    websiteProject: 'Corporate Website Redesign',
    websiteTotal: 18000,
    websiteAdvance: 8000,
    websiteDeliveryDate: '2026-09-25',
    websiteDueDate: '2026-10-05',
    websiteStatus: 'partially_paid',
    websiteStage: 'work_in_progress',
    maintenanceEnabled: true,
    maintenanceAmount: 1500,
    maintenanceStartDate: '2026-11-01',
    maintenanceNextDue: '2026-11-01',
    maintenanceStatus: 'upcoming',
    socialPackage: 'Growth Package',
    socialAmount: 8000,
    socialStartDate: '2026-08-01',
    socialNextDue: '2026-10-10',
    socialAdvance: 4000,
    socialOutstanding: 4000,
    socialStatus: 'partially_paid',
    totalContractValue: 44000,
    totalPaid: 12000,
    totalDue: 14000,
    overallStatus: 'partially_paid',
  },
  {
    id: 'c2',
    name: 'Priya Sharma',
    business: 'Green Fresh Foods',
    phone: '+91 87654 32109',
    email: 'priya@greenfresh.in',
    service: 'social_media',
    createdAt: '2026-06-15',
    socialPackage: 'Standard Package',
    socialAmount: 6000,
    socialStartDate: '2026-06-15',
    socialNextDue: '2026-11-15',
    socialAdvance: 6000,
    socialOutstanding: 0,
    socialStatus: 'paid',
    totalContractValue: 6000,
    totalPaid: 6000,
    totalDue: 0,
    overallStatus: 'paid',
  },
  {
    id: 'c3',
    name: 'Vikram Singh',
    business: 'Sunrise Properties',
    phone: '+91 76543 21098',
    email: 'vikram@sunriseprop.in',
    service: 'website',
    createdAt: '2026-05-20',
    websiteProject: 'Real Estate Portal',
    websiteTotal: 25000,
    websiteAdvance: 10000,
    websiteDeliveryDate: '2026-08-30',
    websiteDueDate: '2026-09-15',
    websiteStatus: 'overdue',
    websiteStage: 'payment_due',
    maintenanceEnabled: true,
    maintenanceAmount: 2000,
    maintenanceStartDate: '2026-10-01',
    maintenanceNextDue: '2026-10-01',
    maintenanceStatus: 'upcoming',
    totalContractValue: 25000,
    totalPaid: 10000,
    totalDue: 15000,
    overallStatus: 'overdue',
  },
  {
    id: 'c4',
    name: 'Kavya Reddy',
    business: 'Metro Gym',
    phone: '+91 65432 10987',
    email: 'kavya@metrogym.in',
    service: 'social_media',
    createdAt: '2026-08-01',
    socialPackage: 'Starter Package',
    socialAmount: 5000,
    socialStartDate: '2026-08-01',
    socialNextDue: '2026-09-05',
    socialAdvance: 0,
    socialOutstanding: 5000,
    socialStatus: 'overdue',
    totalContractValue: 5000,
    totalPaid: 0,
    totalDue: 5000,
    overallStatus: 'overdue',
  },
  {
    id: 'c5',
    name: 'Rohan Gupta',
    business: 'Bloom Beauty',
    phone: '+91 54321 09876',
    email: 'rohan@bloombeauty.in',
    service: 'website',
    createdAt: '2026-04-01',
    websiteProject: 'Beauty E-Commerce Store',
    websiteTotal: 12000,
    websiteAdvance: 12000,
    websiteDeliveryDate: '2026-07-01',
    websiteDueDate: '2026-07-01',
    websiteStatus: 'paid',
    websiteStage: 'fully_paid',
    maintenanceEnabled: true,
    maintenanceAmount: 1000,
    maintenanceStartDate: '2026-08-01',
    maintenanceNextDue: '2026-10-01',
    maintenanceStatus: 'due',
    totalContractValue: 13000,
    totalPaid: 13000,
    totalDue: 1000,
    overallStatus: 'partially_paid',
  },
  {
    id: 'c6',
    name: 'Neha Kapoor',
    business: 'City Motors',
    phone: '+91 43210 98765',
    email: 'neha@citymotors.in',
    service: 'both',
    createdAt: '2026-09-01',
    websiteProject: 'Automotive Showroom Website',
    websiteTotal: 35000,
    websiteAdvance: 15000,
    websiteDeliveryDate: '2026-10-30',
    websiteDueDate: '2026-11-05',
    websiteStatus: 'partially_paid',
    websiteStage: 'advance_received',
    maintenanceEnabled: false,
    socialPackage: 'Premium Package',
    socialAmount: 10000,
    socialStartDate: '2026-09-01',
    socialNextDue: '2026-10-01',
    socialAdvance: 5000,
    socialOutstanding: 5000,
    socialStatus: 'partially_paid',
    totalContractValue: 50000,
    totalPaid: 20000,
    totalDue: 25000,
    overallStatus: 'partially_paid',
  },
];

export const payments: Payment[] = [
  // TechStar - website advance
  {
    id: 'p1',
    clientId: 'c1',
    clientName: 'Arjun Mehta',
    business: 'TechStar Solutions',
    service: 'website',
    paymentType: 'website_onetime',
    totalAmount: 18000,
    received: 8000,
    remaining: 10000,
    date: '2026-07-10',
    dueDate: '2026-10-05',
    method: 'upi',
    transactionId: 'UPI2607100001',
    status: 'partially_paid',
  },
  // TechStar - social media
  {
    id: 'p2',
    clientId: 'c1',
    clientName: 'Arjun Mehta',
    business: 'TechStar Solutions',
    service: 'social_media',
    paymentType: 'social_media',
    totalAmount: 8000,
    received: 4000,
    remaining: 4000,
    date: '2026-09-01',
    dueDate: '2026-10-10',
    method: 'bank_transfer',
    transactionId: 'NEFT2609010012',
    status: 'partially_paid',
  },
  // Green Fresh - social paid
  {
    id: 'p3',
    clientId: 'c2',
    clientName: 'Priya Sharma',
    business: 'Green Fresh Foods',
    service: 'social_media',
    paymentType: 'social_media',
    totalAmount: 6000,
    received: 6000,
    remaining: 0,
    date: '2026-09-01',
    dueDate: '2026-09-15',
    method: 'upi',
    transactionId: 'UPI2609010045',
    status: 'paid',
  },
  // Sunrise Properties - website overdue
  {
    id: 'p4',
    clientId: 'c3',
    clientName: 'Vikram Singh',
    business: 'Sunrise Properties',
    service: 'website',
    paymentType: 'website_onetime',
    totalAmount: 25000,
    received: 10000,
    remaining: 15000,
    date: '2026-05-20',
    dueDate: '2026-09-15',
    method: 'bank_transfer',
    transactionId: 'NEFT2605200088',
    status: 'overdue',
  },
  // Metro Gym - overdue
  {
    id: 'p5',
    clientId: 'c4',
    clientName: 'Kavya Reddy',
    business: 'Metro Gym',
    service: 'social_media',
    paymentType: 'social_media',
    totalAmount: 5000,
    received: 0,
    remaining: 5000,
    date: '2026-08-01',
    dueDate: '2026-09-05',
    method: 'upi',
    status: 'overdue',
  },
  // Bloom Beauty - website paid
  {
    id: 'p6',
    clientId: 'c5',
    clientName: 'Rohan Gupta',
    business: 'Bloom Beauty',
    service: 'website',
    paymentType: 'website_onetime',
    totalAmount: 12000,
    received: 12000,
    remaining: 0,
    date: '2026-06-30',
    dueDate: '2026-07-01',
    method: 'bank_transfer',
    transactionId: 'NEFT2606300067',
    status: 'paid',
  },
  // Bloom Beauty - maintenance due
  {
    id: 'p7',
    clientId: 'c5',
    clientName: 'Rohan Gupta',
    business: 'Bloom Beauty',
    service: 'website',
    paymentType: 'website_maintenance',
    totalAmount: 1000,
    received: 0,
    remaining: 1000,
    date: '2026-09-01',
    dueDate: '2026-10-01',
    method: 'upi',
    status: 'due',
  },
  // City Motors - website advance
  {
    id: 'p8',
    clientId: 'c6',
    clientName: 'Neha Kapoor',
    business: 'City Motors',
    service: 'website',
    paymentType: 'website_onetime',
    totalAmount: 35000,
    received: 15000,
    remaining: 20000,
    date: '2026-09-01',
    dueDate: '2026-11-05',
    method: 'cash',
    status: 'partially_paid',
  },
  // City Motors - social media
  {
    id: 'p9',
    clientId: 'c6',
    clientName: 'Neha Kapoor',
    business: 'City Motors',
    service: 'social_media',
    paymentType: 'social_media',
    totalAmount: 10000,
    received: 5000,
    remaining: 5000,
    date: '2026-09-01',
    dueDate: '2026-10-01',
    method: 'upi',
    status: 'partially_paid',
  },
];

export const formatCurrency = (amount: number) =>
  `₹${amount.toLocaleString('en-IN')}`;

export const formatDate = (dateStr: string) => {
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
};

export const daysUntil = (dateStr: string) => {
  const today = new Date('2026-09-06');
  const due = new Date(dateStr);
  return Math.ceil((due.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
};

export const statusLabel: Record<string, string> = {
  paid: 'PAID',
  partially_paid: 'PARTIAL',
  due: 'DUE',
  overdue: 'OVERDUE',
  upcoming: 'UPCOMING',
};

export const pipelineStageLabel: Record<string, string> = {
  lead: 'Lead',
  advance_received: 'Advance Received',
  work_in_progress: 'Work in Progress',
  payment_due: 'Payment Due',
  fully_paid: 'Fully Paid',
};
